[package]
name = "kurotto-generator"
version = "0.1.0"
authors = ["Rhizotome <dam.elalami@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
